/*
CREATE SCHEMA BAMAZON
*/

/*
CREATE TABLE PRODUCTS (
	ID_ITEM INT(100) AUTO_INCREMENT NOT NULL,
    ID_DEPARTMENT INT(100) NOT NULL,
    PRODUCT_NAME VARCHAR(70) NOT NULL,
    PRICE FLOAT(7,2) NOT NULL,
    STOCK INT(10),
    PRODUCT_SALES FLOAT(7,2),
    PRIMARY KEY (ID_ITEM)
);
*/

/*
INSERT INTO PRODUCTS (ID_DEPARTMENT, PRODUCT_NAME, PRICE, STOCK) VALUES('3','Flat Panel TV','599.99','400')
INSERT INTO PRODUCTS (ID_DEPARTMENT, PRODUCT_NAME, PRICE, STOCK) VALUES('3','Radio','99.99','200');
INSERT INTO PRODUCTS (ID_DEPARTMENT, PRODUCT_NAME, PRICE, STOCK) VALUES('3','Cell Phone','299.99','800');
INSERT INTO PRODUCTS (ID_DEPARTMENT, PRODUCT_NAME, PRICE, STOCK) VALUES('1','Microwave Oven','199.99','250');
INSERT INTO PRODUCTS (ID_DEPARTMENT, PRODUCT_NAME, PRICE, STOCK) VALUES('1','Dining Table','499.99','100');
INSERT INTO PRODUCTS (ID_DEPARTMENT, PRODUCT_NAME, PRICE, STOCK) VALUES('1','Dining Chair','199.99','400');
INSERT INTO PRODUCTS (ID_DEPARTMENT, PRODUCT_NAME, PRICE, STOCK) VALUES('2','T-Shirt','9.99','200');
INSERT INTO PRODUCTS (ID_DEPARTMENT, PRODUCT_NAME, PRICE, STOCK) VALUES('2','Blouse','24.99','300');
INSERT INTO PRODUCTS (ID_DEPARTMENT, PRODUCT_NAME, PRICE, STOCK) VALUES('2','Jeans','54.99','600');
INSERT INTO PRODUCTS (ID_DEPARTMENT, PRODUCT_NAME, PRICE, STOCK) VALUES('2','Tennis Shoes','75','800');
*/

/* UPDATE PRODUCTS SET PRICE = PRICE || ".99" WHERE ID_ITEM > 0; 
*/


SELECT PRD.*, DPT.* 
FROM PRODUCTS PRD
	INNER JOIN DEPARTMENTS DPT ON DPT.ID_DEPARTMENT = PRD.ID_DEPARTMENT;

/*
CREATE TABLE DEPARTMENTS (
	ID_DEPARTMENT INT(100) AUTO_INCREMENT NOT NULL,
    DEPARTMENT_NAME VARCHAR(70) NOT NULL,
    OVERHEAD_COST FLOAT(7,2),
    PRIMARY KEY (ID_DEPARTMENT)
);
*/

/*
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES('Home Goods');
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES('Clothing');
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES('Electronics');
*/

SELECT *
FROM DEPARTMENTS;
